trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Descargando Power Platform CLI..."
    curl -L https://aka.ms/PowerPlatformCLI-linux -o pac-linux.tar.gz
    mkdir -p $HOME/.local/bin
    tar -xzf pac-linux.tar.gz -C $HOME/.local/bin
    export PATH=$HOME/.local/bin:$PATH
    echo "Verificando instalación de pac..."
    pac --version
  displayName: 'Instalar Power Platform CLI'

- script: |
    export PATH=$HOME/.local/bin:$PATH
    echo "Empaquetando solución..."
    mkdir -p output
    pac solution pack --folder source-solution --zipfile output/solution.zip
  displayName: 'Empaquetar solución'

# Aquí podés agregar más pasos para publicar el zip, o lo que necesites.
