trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install -g @microsoft/powerplatform-cli
  displayName: 'Install Power Platform CLI'

- script: |
    pac --version
    pac solution pack --folder source-solution --zipfile output/solution.zip
    pac solution unpack --zipfile output/solution.zip --folder output/unpack
  displayName: 'Pack and Unpack solution locally'

- script: echo "Add static analysis or tests here"
  displayName: 'Run static validation'
