trigger:
- master  

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    echo "Instalando Power Platform CLI..."
    curl -L https://aka.ms/powerplatformcli/linux | bash
    pac --version
  displayName: 'Instalar Power Platform CLI'

- script: |
    echo "Empaquetando solución desde ./source-solution a solution.zip"
    pac solution pack --folder ./source-solution --zipfile ./solution.zip
  displayName: 'Empaquetar solución'

- script: |
    echo "Desempaquetando solution.zip a ./unpacked-solution"
    mkdir unpacked-solution
    pac solution unpack --zipfile ./solution.zip --folder ./unpacked-solution
  displayName: 'Desempaquetar solución'

- script: |
    if [ ! -d "./unpacked-solution" ]; then
      echo "❌ Error: La solución no fue desempaquetada correctamente"
      exit 1
    else
      echo "✅ Solución desempaquetada correctamente"
    fi
  displayName: 'Validar desempaquetado'
